baseURL = "https://gooy.site/"
defaultContentLanguage = "fa"
title = "Gooy"
theme = ["gooy-theme"]
author = "MParvin"
ga_analytics = ""
ga_verify = ""
enableRobotsTXT = true
canonifyURLs = true

[languages.fa]
locale = "fa-IR"
label = "فارسی"
weight = 1

[pagination]
pagerSize = 10

[permalinks]
  posts = "/posts/:slug/"
  pages = "/:slug/"

[taxonomies]
  category = "categories"
  subcategory = "subcategories"
  tag = "tags"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false

[params]
rtl = true
defaultMode = "dark"
defaultImage = "default-post.svg"

[[params.sidebar.links]]
  name = "مستندات برنامه نویسی"
  url = "https://docs.gooy.site"
  icon = "docs"

[[params.sidebar.links]]
  name = "w3school برای اینترنت ملی"
  url = "https://w3s.gooy.site"
  icon = "globe"
